### ISSUE TITLE
test data file not found

### ISSUE THREAD

**Issue by JoeLee2013** [tobegit3hub/tensorflow_template_application#13]
Traceback (most recent call last):
  File "./dense_classifier.py", line 420, in <module>
    main()
  File "./dense_classifier.py", line 349, in main
    inference_data = np.genfromtxt(inference_test_file_name, delimiter=",")
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1451, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: ./data/cancer_test.csv not found.

the path is './data/cancer/cancer_test.csv', not './data/cancer_test.csv'

**Comment by tobegit3hub** [comment]
Thanks @JoeLee2013 and you're right. I have refactor the code and changed the directories of the data.

It has been fixed yesterday. Do you mind `git pull` for latest code and help to test again?

**Comment by JoeLee2013** [comment]
@tobegit3hub It's OK now. Thanks!

**Comment by tobegit3hub** [comment]
Good to hear that 🎉
